spring.application.name=sim-core

# application run port
server.port=8080

# mybatis
mybatis.configuration.map-underscore-to-camel-case=true

# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/etg?characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# email
email.user=qinphy@126.com
email.code=DUYUYTQREULDMZIW
email.host=smtp.126.com
email.auth=true

# upload settings
workspace.path=D:/Simulation/

# set software name
software.name=EVs-Traffic-Grid
